In [1]:
import sys
import os
sys.path.append(os.path.abspath(".."))

from spark_config import SparkConfig
from logger import LoggerConfig
from io_config import IOConfig
from platform_app import PlatformApp

In [2]:
logger = LoggerConfig().setup_logger(log_dir=IOConfig.LOG_DIR)
spark = SparkConfig.create_spark(app_name="SQL in Spark", logger=logger, use_databricks=True)
app = PlatformApp(spark=spark, logger=logger, catalog_name="databricks_toturial")

2026-03-05 10:17:13 | INFO     | Logging configured: level=DEBUG, format=colored
2026-03-05 10:17:15 | INFO     | Connected to Databricks via Spark Connect.
2026-03-05 10:17:15 | INFO     | Initializing Data Platform...
2026-03-05 10:17:15 | INFO     | Spark session initialized

In [6]:
df = (
        spark.read.
        format("csv").
        option("header", True).
        option("inferSchema", True).
        csv("/Volumes/databricks_toturial/source/source_data/movies")
    )
df.show(n=10, truncate=False)

+-------------------------------------------+---------+------------+-----------+-------------------------+-------+--------+---------+--------+--------+
|title                                      |industry |release_year|imdb_rating|studio                   |budget |revenue |unit     |currency|language|
+-------------------------------------------+---------+------------+-----------+-------------------------+-------+--------+---------+--------+--------+
|Pather Panchali                            |Bollywood|1955        |8.3        |Government of West Bengal|70000.0|100000.0|Thousands|INR     |Bengali |
|Doctor Strange in the Multiverse of Madness|Hollywood|2022        |7          |Marvel Studios           |200.0  |954.8   |Millions |USD     |English |
|Thor: The Dark World                       |Hollywood|2013        |6.8        |Marvel Studios           |165.0  |644.8   |Millions |USD     |English |
|Thor: Ragnarok                             |Hollywood|2017        |7.9        |Marvel Studios           |180.0  |854.0   |Millions |USD     |English |
|Thor: Love and Thunder                     |Hollywood|2022        |6.8        |Marvel Studios           |250.0  |670.0   |Millions |USD     |English |
|The Shawshank Redemption                   |Hollywood|1994        |9.3        |Castle Rock Entertainment|25.0   |73.3    |Millions |USD     |English |
|Interstellar                               |Hollywood|2014        |8.6        |Warner Bros. Pictures    |165.0  |701.8   |Millions |USD     |English |
|The Pursuit of Happyness                   |Hollywood|2006        |8          |Columbia Pictures        |55.0   |307.1   |Millions |USD     |English |
|Gladiator                                  |Hollywood|2000        |8.5        |Universal Pictures       |103.0  |460.5   |Millions |USD     |English |
|Titanic                                    |Hollywood|1997        |7.9        |Paramount Pictures       |200.0  |2202.0  |Millions |USD     |English |
+-------------------------------------------+---------+------------+-----------+-------------------------+-------+--------+---------+--------+--------+
only showing top 10 rows

In [7]:
df.createOrReplaceTempView("temp_movies")
df_marvel = spark.sql("""
    SELECT  *
    FROM    temp_movies
    WHERE   studio = 'Marvel Studios'
""")
df_marvel.show(n=10, truncate=False)

+-------------------------------------------+---------+------------+-----------+--------------+------+-------+--------+--------+--------+
|title                                      |industry |release_year|imdb_rating|studio        |budget|revenue|unit    |currency|language|
+-------------------------------------------+---------+------------+-----------+--------------+------+-------+--------+--------+--------+
|Doctor Strange in the Multiverse of Madness|Hollywood|2022        |7          |Marvel Studios|200.0 |954.8  |Millions|USD     |English |
|Thor: The Dark World                       |Hollywood|2013        |6.8        |Marvel Studios|165.0 |644.8  |Millions|USD     |English |
|Thor: Ragnarok                             |Hollywood|2017        |7.9        |Marvel Studios|180.0 |854.0  |Millions|USD     |English |
|Thor: Love and Thunder                     |Hollywood|2022        |6.8        |Marvel Studios|250.0 |670.0  |Millions|USD     |English |
|Avengers: Endgame                          |Hollywood|2019        |8.4        |Marvel Studios|400.0 |2798.0 |Millions|USD     |English |
|Avengers: Infinity War                     |Hollywood|2018        |8.4        |Marvel Studios|400.0 |2048.0 |Millions|USD     |English |
|Captain America: The First Avenger         |Hollywood|2011        |6.9        |Marvel Studios|216.7 |370.6  |Millions|USD     |English |
|Captain America: The Winter Soldier        |Hollywood|2014        |7.8        |Marvel Studios|177.0 |714.4  |Millions|USD     |English |
+-------------------------------------------+---------+------------+-----------+--------------+------+-------+--------+--------+--------+

## SQL Using %sql

In [ ]:
%sql
SELECT  *
FROM    temp_movies
WHERE   studio = 'Marvel Studios'

DataFrame[title: string, industry: string, release_year: int, imdb_rating: string, studio: string, budget: double, revenue: double, unit: string, currency: string, language: string]

In [10]:
logger = LoggerConfig().setup_logger(log_dir=IOConfig.LOG_DIR)
spark = SparkConfig.create_spark(app_name="SQL in Spark", logger=logger, use_databricks=True)
app = PlatformApp(spark=spark, logger=logger, catalog_name="databricks_toturial")

2026-03-05 10:41:38 | INFO     | Logging configured: level=DEBUG, format=colored
2026-03-05 10:41:38 | INFO     | Connected to Databricks via Spark Connect.
2026-03-05 10:41:38 | INFO     | Initializing Data Platform...
2026-03-05 10:41:38 | INFO     | Spark session initialized

In [13]:
from pyspark.sql import functions as F, types as T

data = [
    ("2017-01-01", 32.0, 6.0, "Rain"),
    ("2017-01-04", None, 9.0, "Sunny"),
    ("2017-01-05", 28.0, None, "Snow"),
    ("2017-01-06", None, 7.0, None),
    ("2017-01-07", 32.0, None, "Rain"),
    ("2017-01-08", None, None, "Sunny"),
    ("2017-01-09", None, None, None),
    ("2017-01-10", 34.1, 8.1, "Cloudy"),
    ("2017-01-11", 40.0, 12.0, "Sunny"),
]

schema = "day string, temperature double, windspeed double, event string"

df = spark.createDataFrame(data, schema)
df = df.withColumn("day", F.to_date("day", "yyyy-MM-dd"))  # normalize to DateType

display(df)

DataFrame[day: date, temperature: double, windspeed: double, event: string]

In [16]:
df.createOrReplaceTempView("weather")

In [19]:
%sql
SELECT      event,
            ROUND(AVG(temperature), 1) AS avg_temp
FROM        weather
GROUP BY    event
ORDER BY    avg_temp DESC;

DataFrame[event: string, avg_temp: double]